## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function


##Open a list for all the functions generated by makeCacheMatrix

makeMatrixCache <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setinverse <- function(solve) m <<- solve
  getinverse <- function() m
  list(set = set, get = get,
       setinverse = setinverse,
       getinverse = getinverse)
}

cacheSolve <- function(x, ...) {
  m <- x$getinverse()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setinverse(m)
  m
}

a <- makeMatrixCache(matrix(1:4,2,2))
a$get
a$getinverse

cacheSolve(a)






