## Put comments here that give an overall description of what your
## functions do

## Write a short comment describing this function


##Open a list for all the functions generated by makeCacheMatrix



x<-matrix(1:4,2,2)

makeCacheMatrix <- function(x) {
  m<-NULL
  setmatrix<-function(y){
    x<<-y
    m<<-NULL
  }
  getmatrix<-function() x
  setinverse<-function(solve) m<<- solve
  getinverse<-function() m
  
  list(setinverse=setinverse, getinverse=getinverse, setmatrix=setmatrix, getmatrix=getmatrix)
  
}



cacheSolve <- function(x, ...) {
  m<-x$getmatrix
  if(!is.null(m)){
    message("getting cached data")
    return(m)}
  matrix<-x$get()
  m<-solve(matrix, ...)
  x$setmatrix(m)
  m
}

